### ISSUE TITLE
buttons are dark even in dark mode

### ISSUE THREAD

**Issue by jamesf-hub** [Futur3Sn0w/futur3f0x#1]
<img width="1728" alt="Screenshot 2024-03-11 at 5 48 04 PM" src="https://github.com/Futur3Sn0w/futur3f0x/assets/43358890/594bd4da-22e2-466d-9b14-b3ec38992d83">

**Comment by Futur3Sn0w** [comment]
This can be fixed by setting `svg.context-properties.content.enabled` to `true` in about:config! 🤩
