### ISSUE TITLE
URL bar isn't vertically centred

### ISSUE THREAD

**Issue by Nosh118** [Futur3Sn0w/futur3f0x#2]
<img width="1119" alt="image" src="https://github.com/Futur3Sn0w/futur3f0x/assets/67752804/6ef6a64a-84ff-4ca0-8572-5e03af99e505">
The URL bar isn't properly centred in the middle of the top transparent bar

**Comment by Futur3Sn0w** [comment]
Nice catch! Fixed in v1.1! 😄
